# -*- coding: utf-8 -*-
"""
Created on Fri June  23 09:28:43 2017

@author: S.Y. Agustsson
"""

import sys
from PyQt5 import QtWidgets as qw, QtCore as qc, uic
import cv2
from BeamProfilerLib.BeamProfilerUI import Ui_MainWindow
from BeamProfilerLib.gui import get_frame, get_devicelist, get_weighted_frame
from BeamProfilerLib import genericfunctions as gfs


def main_old():
    app = qw.QApplication(sys.argv)
    w = BeamProfilerMainApp()
    # w.setGeometry(300, 100, 640, 480)
    w.show()
    app.exec_()

def main():
    # used to see errors generated by PyQt5 in pycharm:
    sys._excepthook = sys.excepthook
    # Set the exception hook to our wrapping function
    sys.excepthook = my_exception_hook

    app = qc.QCoreApplication.instance()
    if app is None:
        app = qw.QApplication(sys.argv)
    # Create handle prg for the Graphic Interface
    prg = BeamProfilerMainApp()
    prg.show()

    try:
        app.exec_()
    except:
        print('exiting')


def my_exception_hook(exctype, value, traceback):
    # Print the error and traceback
    print(exctype, value, traceback)
    # Call the normal Exception hook after
    sys._excepthook(exctype, value, traceback)
    sys.exit(1)


class BeamProfilerMainApp(qw.QMainWindow, Ui_MainWindow):
    CAMERA_INDEX = 1

    def __init__(self):
        super(BeamProfilerMainApp, self).__init__()

        self.setupUi(self)

        self.devicedict = {}
        self.init_devices()

        self.timer = qc.QTimer()
        self.timer.setInterval(10)
        self.timer.timeout.connect(self.on_timer)
        self.frame = None
        self.camera = cv2.VideoCapture(self.CAMERA_INDEX)

        self.show()

    def init_devices(self):
        self.devicedict = get_devicelist()
        for key, item in self.devicedict.items():
            self.select_device_combobox.addItem(key)

    def init_camera(self):
        # if isinstance(self.camera, cv2.VideoCapture()):
        #     del self.camera
        self.camera = cv2.VideoCapture(self.CAMERA_INDEX)

    @qc.pyqtSlot()
    def select_device(self):
        self.timer.stop()
        self.camera_name = self.select_device_combobox.currentText()
        self.CAMERA_INDEX = self.devicedict[self.camera_name]['port']
        print('using camera {0} - {1}'.format(self.CAMERA_INDEX, self.camera_name))
        print(self.select_device_combobox.currentText())
        self.init_camera()
        self.timer.start()

    @qc.pyqtSlot()
    def on_timer(self):
        self.refresh_videoframe()

    def refresh_videoframe(self, _return=False):  # todo: work on this
        # frame = get_frame(self.camera, color='RGB')
        alpha = self.alpha_persistence_slide.value()
        self.frame = get_weighted_frame(self.camera, alpha=alpha, color='RGB')
        if len(self.frame[0][0]) == 3:
            self.cam_window.setImage(self.frame, axes={'x': 1, 'y': 0, 'c': 2})
        else:
            print(len(self.frame[0][0]))
            self.cam_window.setImage(self.frame, axes={'x': 1, 'y': 0})
        if _return:
            return self.frame

    @qc.pyqtSlot()
    def save_screenshot(self):
        print('it works: save screenshot')
        saveframe = self.frame
        filename = gfs.choose_save_filename(initialdir='c://')
        gfs.save_obj(saveframe,filename)
        print('Saved frame as: {}'.format(filename))

    @qc.pyqtSlot()
    def start_recording(self):
        print('it works: start recording')

    @qc.pyqtSlot()
    def startstop_videostream(self):
        print('it works: start aquisition')
        self.timer.start()
        print('Timer Started')

if __name__ == "__main__":

    recompile = True
    if recompile:
        print('recompiling')
        ui_file = 'C:\py_code\BeamProfiler\BeamProfilerLib\BeamProfilerUI.ui'
        ui_dir = 'C:\py_code\BeamProfiler\BeamProfilerLib'
        # py_file = open('C:\py_code\BeamProfiler\BeamProfilerLib\BeamProfilerUI.py', 'w')
        uic.compileUiDir(ui_dir, execute=True)
        print('done')

    main()
